### ISSUE TITLE
`ruff server` and `pyright` at the same time.

### ISSUE THREAD

**Issue by brurucy** [jupyter-lsp/jupyterlab-lsp#1094] opened 2024-07-17 17:01 UTC
## Description

I cannot have both `ruff server` and `pyright` running at the same time, it is annoying.

## Reproduce

`jupyter_server_config.py`:
```python
c = get_config()  # noqa

c.ServerApp.open_browser = False
c.LanguageServerManager.autodetect = False
c.LanguageServerManager.language_servers = {
    "pyright": {
        "argv": ["pyright-langserver", "--stdio"],
        "languages": ["python"],
        "version": 2,
        "mime_types": ["text/python", "text/ipython"],
        "display_name": "pyright",
    },
    "ruff": {
        "argv": ["ruff", "server", "--preview"],
        "languages": ["python"],
        "version": 2,
        "mime_types": ["text/python", "text/ipython"],
        "display_name": "ruff",
    },
}
```

`settings`:
```
"language_servers": {
   "pyright": {
        "priority": 500,
        "serverSettings": {}
     },
     "ruff": {
         "priority": 500,
         "serverSettings": {}
     }
},
```

## Expected behavior

To have suggestions from both `pyright` and `ruff`.

## Context

- JupyterLab version: `4.2.3`

**Comment by krassowski** [comment] 2024-07-17 17:47
PRs to enable this would be warmly welcome!

I will close this as duplicate of https://github.com/jupyter-lsp/jupyterlab-lsp/issues/708 and of https://github.com/jupyter-lsp/jupyterlab-lsp/issues/437.

**Closed by krassowski** 2024-07-17 17:47 UTC
